---
- name: install dma
  pkgng:
    name: dma
    cached: yes

- name: configure mailwrapper to use dma
  copy:
    src: mailer.conf
    dest: /etc/mail/mailer.conf

- name: configure dma
  template:
    src: dma.conf.j2
    dest: /usr/local/etc/dma/dma.conf

- name: periodically flush dma's queue
  cron:
    name: flush queue
    minute: '*/15'
    job: 'test -x /usr/local/libexec/dma && /usr/local/libexec/dma -q'

- name: set up aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^#?{{ item.user }}:'
    line: "{{ item.user }}: {{ item.email }}"
  with_items: "{{ forwarding }}"
  notify:
    - run newaliases
