---
- name: install transmission
  pkgng:
    name:
      - transmission-daemon
      - transmission-utils
    cached: true

- name: start transmission
  service:
    name: transmission
    enabled: true
    state: started

- name: fix permissions
  file:
    path: "{{ transmission_home }}"
    owner: transmission
    group: transmission

- name: ensure there's enough space for the receive buffer
  sysctl:
    name: kern.ipc.maxsockbuf
    # This fixes the error 'UDP failed to set receive buffer: No buffer space
    # available'. Minimum value to cover the default value and how much
    # Transmission wants. See: https://ostreff.info/archives/134413
    value: 5242880
  notify:
    - reload transmission

- name: fix the config
  merge_json:
    path: "{{ transmission_home }}/settings.json"
    data:
      rpc-bind-address: "127.0.0.1"
      rpc-enabled: true
      rpc-whitelist: "127.0.0.1"
      rpc-whitelist-enabled: true
    indent: 4
  notify:
    - reload transmission
