---
- name: reload nginx
  service:
    name: nginx
    enabled: true
    state: reloaded

- name: generate missing certificates
  command:
    argv:
      - "{{ acme_client_root }}/acme-domain-renew"
      - "-c"
      - "{{ acme_client_root }}"
      - "-w"
      - "{{ acme_challenge_dir }}"
      - "-t"
      - "{{ tls_root }}"
