---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common

- hosts: "!mailservers"
  remote_user: keith
  become: true
  roles:
    - dma

- hosts: buildservers
  remote_user: keith
  become: true
  roles:
    - buildserver
  tags:
    - buildserver

- hosts: feedreaders
  remote_user: keith
  become: true
  roles:
    - feedreader
  tags:
    - feedreader

- hosts: mailservers
  remote_user: keith
  become: true
  roles:
    - mailserver
  tags:
    - mailserver

- hosts: nameservers
  remote_user: keith
  become: true
  roles:
    - nameserver
  tags:
    - nameserver

- hosts: torrent
  remote_user: keith
  become: true
  roles:
    - torrent
  tags:
    - torrent

- hosts: webservers
  remote_user: keith
  become: true
  roles:
    - webserver
  tags:
    - webserver

- hosts: xmpp
  remote_user: keith
  become: true
  roles:
    - xmpp
  tags:
    - xmpp
