---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common

- import_playbook: acme.yml
- import_playbook: dbservers.yml
- import_playbook: mailservers.yml
- import_playbook: webservers.yml
- import_playbook: nameservers.yml
- import_playbook: xmpp.yml
- import_playbook: torrent.yml
