---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common
    - tarsnap

- hosts: "!mailservers"
  remote_user: keith
  become: true
  roles:
    - dma

- hosts: dav
  remote_user: keith
  become: true
  roles:
    - dav
  tags:
    - dav

- hosts: feedreaders
  remote_user: keith
  become: true
  roles:
    - feedreader
  tags:
    - feedreader

- hosts: mailservers
  remote_user: keith
  become: true
  roles:
    - mailserver
  tags:
    - mailserver

- hosts: nameservers
  remote_user: keith
  become: true
  roles:
    - nameserver
  tags:
    - nameserver

- hosts: repos
  remote_user: keith
  become: true
  roles:
    - cgit
  tags:
    - repo

- hosts: torrent
  remote_user: keith
  become: true
  roles:
    - torrent
  tags:
    - torrent

- hosts: webmail
  remote_user: keith
  become: true
  roles:
    - webmail
  tags:
    - webmail

- hosts: webservers
  remote_user: keith
  become: true
  roles:
    - acme
  tags:
    - webserver

- hosts: xmpp
  remote_user: keith
  become: true
  roles:
    - xmpp
  tags:
    - xmpp
