---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common

- include: acme.yml
- include: dbservers.yml
- include: mailservers.yml
- include: webservers.yml
- include: nameservers.yml
- include: xmpp.yml
