---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common

#- hosts: dbservers
#  roles:
#    - dbservers

- include: mailservers.yml
- include: nameservers.yml

#- hosts: webservers
#  roles:
#    - webservers
