---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common

#- hosts: dbservers
#  roles:
#    - dbservers

- hosts: mailservers
  remote_user: keith
  become: true
  roles:
    - mailserver

#- hosts: nameservers
#  roles:
#    - nameservers
#
#- hosts: webservers
#  roles:
#    - webservers
