---
- hosts: all
  remote_user: keith
  become: true
  roles:
    - common

- include: acme.yml
- include: dbservers.yml
- include: mailservers.yml
- include: nameservers.yml
- include: buildservers.yml

#- hosts: webservers
#  roles:
#    - webservers
