---
- name: install dovecot
  pkgng:
    name:
      - dovecot
      - dovecot-pigeonhole
    cached: true

- name: create diffie-hellman parameters
  openssl_dhparam:
    path: "{{ dovecot_root }}/dh.pem"
    mode: 0640
    owner: dovecot
    group: dovecot
  notify:
    - restart dovecot

- name: deploy dovecot.conf
  template:
    src: dovecot.conf.j2
    dest: "{{ dovecot_root }}/dovecot.conf"
    mode: 0644
  notify:
    - restart dovecot

- name: start dovecot
  service:
    name: dovecot
    enabled: true
    state: started

- name: restart on cert deployment
  lineinfile:
    path: "{{ acme_client_root }}/deploy.sh"
    state: present
    insertafter: EOF
    line: "service dovecot reload"
