---
- name: install dovecot
  pkgng:
    name: '{{ item }}'
    cached: yes
  with_items:
    - dovecot
    - dovecot-pigeonhole

- name: create diffie-hellman parameters
  shell: "dd if=/var/db/dovecot/ssl-parameters.dat bs=1 skip=88 | openssl dhparam -inform der > dh.pem"
  args:
    chdir: "{{ dovecot_root }}"
    creates: dh.pem
  notify:
    - restart dovecot

- name: make the parameters available to dovecot only
  file:
    name: "{{ dovecot_root }}/dh.pem"
    mode: 0640
    owner: dovecot
    group: dovecot

- name: deploy dovecot.conf
  template:
    src: dovecot.conf.j2
    dest: "{{ dovecot_root }}/dovecot.conf"
    mode: 0644
  notify:
    - restart dovecot

- name: start dovecot
  service:
    name: dovecot
    enabled: yes
    state: started

- name: restart on cert deployment
  lineinfile:
    path: "{{ acme_client_root }}/deploy.sh"
    state: present
    insertafter: EOF
    line: "service dovecot reload"
