---
- name: install packages
  pkgng:
    name: '{{ item }}'
    cached: yes
  with_items:
    - postfix
#   - postfix-policyd-spf-perl

- name: ensure the postfix configuration root exists
  file:
    dest: "{{ postfix_root }}"
    state: directory

- name: deploy master.cf
  copy:
    src: master.cf
    dest: "{{ postfix_root }}"
    mode: 0644
  notify:
    - restart postfix

- name: deploy main.cf
  template:
    src: main.cf.j2
    dest: "{{ postfix_root }}/main.cf"
    mode: 0644
  notify:
    - restart postfix

- name: start postfix
  service:
    name: postfix
    enabled: yes
    state: started
