---
- name: install packages
  pkgng:
    name:
      - postfix
      - sqlite3
      - py27-sqlite3
    cached: true

- name: ensure the postfix configuration root exists
  file:
    dest: "{{ postfix_root }}"
    state: directory

- name: deploy socketmap
  copy:
    src: socketmap-sql
    dest: /usr/local/libexec
    mode: 0755

- name: deploy socketmap config
  template:
    src: socketmap-sql.ini.j2
    dest: /usr/local/etc/socketmap-sql.ini
  notify:
    - restart postfix

- name: deploy master.cf
  copy:
    src: master.cf
    dest: "{{ postfix_root }}"
    mode: 0644
  notify:
    - restart postfix

- name: deploy main.cf
  template:
    src: main.cf.j2
    dest: "{{ postfix_root }}/main.cf"
    mode: 0644
  notify:
    - restart postfix

- name: initialise virtual mailbox database
  command: sqlite3 {{ vbox_db_path }}
  args:
    creates: "{{ vbox_db_path }}"
    stdin: "{{ lookup('file', 'virtual.sql') }}"

- name: configure mailwrapper to use postfix
  copy:
    src: mailer.conf
    dest: /etc/mail/mailer.conf

- name: start postfix
  service:
    name: postfix
    enabled: true
    state: started

- name: restart on cert deployment
  lineinfile:
    path: "{{ acme_client_root }}/deploy.sh"
    state: present
    insertafter: EOF
    line: "service postfix reload"

- name: ensure dma isn't installed
  pkgng:
    name: dma
    state: absent
