---
- name: install rspamd
  pkgng:
    name: rspamd
    cached: true

- name: copy up rspamd config
  copy:
    src: "rspamd/local.d"
    dest: "{{ rspamd_root }}"
  notify:
    - restart rspamd

- name: create dkim key directory
  file:
    dest: /var/db/rspamd/dkim
    state: directory
    owner: rspamd
    group: rspamd
    mode: "750"

- name: deploy dkim keys
  copy:
    dest: "/var/db/rspamd/dkim/{{ item.key }}.default.key"
    owner: rspamd
    group: rspamd
    mode: "640"
    content: "{{ item.value }}"
  loop: "{{ dkim_keys | dict2items }}"
