---
- name: install rspamd
  pkgng:
    name: rspamd
    cached: true

- name: create config directories
  file:
    dest: "{{ rspamd_root }}/{{ item }}"
    state: directory
  loop:
    - local.d
    - override.d

- name: copy up rspamd config
  copy:
    src: "{{ item }}"
    dest: "{{ rspamd_root }}/local.d/{{ item | basename }}"
  with_fileglob:
    - "rspamd.local/*"
  notify:
    - restart rspamd

- name: create dkim key directory
  file:
    dest: /var/db/rspamd/dkim
    state: directory
    owner: rspamd
    group: rspamd
    mode: "750"

- name: deploy dkim keys
  copy:
    dest: "/var/db/rspamd/dkim/{{ item.key }}.default.key"
    owner: rspamd
    group: rspamd
    mode: "640"
    content: "{{ item.value }}"
  loop: "{{ dkim_keys | dict2items }}"
