---
- name: install rspamd
  pkgng:
    name: rspamd
    cached: true

- name: copy up rspamd config
  copy:
    src: "rspamd/local.d"
    dest: "{{ rspamd_root }}"
  notify:
    - restart rspamd

- name: create sieve directory
  file:
    dest: "{{ dovecot_root }}/sieve"
    state: directory
    mode: "755"

- name: "copy up sieve"
  copy:
    src: "{{ item }}"
    dest: "{{ dovecot_root }}/sieve"
    mode: "644"
  register: sieves
  with_fileglob:
    - "*.sieve"

- name: "compile sieve"
  command:
    argv:
      - sievec
      - "{{ item }}"
  loop: "{{ sieves.results | rejectattr('changed', 'false') | map(attribute='dest') | list }}"

- name: copy up antispam scripts
  copy:
    src: "{{ item }}"
    dest: "{{ dovecot_libexec }}"
    owner: rspamd
    group: rspamd
    mode: "755"
  with_fileglob:
    - "learn-*"

- name: create dkim key directory
  file:
    dest: /var/db/rspamd/dkim
    state: directory
    owner: rspamd
    group: rspamd
    mode: "750"

- name: deploy dkim keys
  copy:
    dest: "/var/db/rspamd/dkim/{{ item.key }}.default.key"
    owner: rspamd
    group: rspamd
    mode: "640"
    content: "{{ item.value }}"
  loop: "{{ dkim_keys | dict2items }}"
  no_log: true
