---
- name: install rspamd
  pkgng:
    name: rspamd
    cached: true

- name: create config directories
  file:
    dest: "{{ rspamd_root }}/{{ item }}"
    state: directory
  loop:
    - local.d
    - override.d

- name: create dkim key directory
  file:
    dest: /var/db/rspamd/dkim
    state: directory
    owner: nobody
    group: nobody

- name: copy up rspamd config
  copy:
    src: "{{ item }}"
    dest: "{{ rspamd_root }}/local.d/{{ item | basename }}"
  with_fileglob:
    - "rspamd.local/*"
  notify:
    - restart rspamd
