---
- name: install packages
  pkgng:
    name:
      - py39-lxml
      - py39-WsgiDAV
    cached: true

- name: ensure the DAV root directory exists
  file:
    name: "{{ dav_root }}"
    state: directory
    owner: www
    group: www
    mode: 0755

- name: deploy supervisor configuration
  template:
    src: dav.ini.j2
    dest: "/usr/local/etc/supervisord.d/dav.ini"
  notify:
    - reload supervisor

- name: deploy vhost
  template:
    src: vhost.j2
    dest: "{{ webserver_config }}/vhosts/{{ dav_site }}"
  notify:
    - reload nginx
