---
- name: install postgresql
  pkgng:
    name:
      - postgresql95-client
      - postgresql95-server
    cached: true

- name: initialise database
  command: /usr/local/etc/rc.d/postgresql initdb
  args:
    creates: /usr/local/pgsql/data

- name: start postgresql
  service:
    name: postgresql
    enabled: true
    state: started
