---
- name: install packages
  pkgng:
    name:
      - python3
      - py36-bjoern
    cached: true

- name: ensure the tools directory exists
  file:
    name: "{{ tools_root }}"
    state: directory
    mode: 0755

- name: ensure the socket directory exists
  file:
    name: "{{ auth_app_sock | dirname }}"
    state: directory
    mode: 0755
    owner: www

- name: copy up the app
  copy:
    src: "{{ item }}"
    dest: "{{ tools_root }}"
  loop:
    - auth.py
    - dovecotauth.py
  notify:
    - touch auth supervisor config file to reload

- name: deploy immortal configuration
  template:
    src: auth.yml.j2
    dest: "/usr/local/etc/immortal/auth.yml"

- name: deploy nginx fragment
  template:
    src: auth_params.j2
    dest: "{{ webserver_config }}/auth_params"
  notify:
    - reload nginx
