---
- name: install packages
  pkgng:
    name:
      - python3
      - py36-bjoern
      - py36-python-pam
    cached: true

- name: ensure the tools directory exists
  file:
    name: "{{ tools_root }}"
    state: directory
    mode: 0755

- name: copy up the app
  copy:
    src: auth.py
    dest: "{{ tools_root }}"
  notify:
    - touch auth supervisor config file to reload

- name: copy up PAM configuration
  copy:
    src: pam_http
    dest: /etc/pam.d/http

- name: deploy immortal configuration
  template:
    src: auth.yml.j2
    dest: "/usr/local/etc/immortal/auth.yml"

- name: deploy nginx fragment
  template:
    src: auth_params.j2
    dest: "{{ webserver_config }}/auth_params"
  notify:
    - reload nginx
