---
- name: install packages
  pkgng:
    name:
      - python3
      - py37-python-pam
    cached: true

- name: ensure the tools directory exists
  file:
    name: "{{ tools_root }}"
    state: directory
    mode: 0755

- name: copy up the app
  copy:
    src: auth.py
    dest: "{{ tools_root }}"
  notify:
    - reload supervisor

- name: copy up PAM configuration
  copy:
    src: pam_http
    dest: /etc/pam.d/http

- name: deploy supervisor configuration
  template:
    src: auth.ini.j2
    dest: "/usr/local/etc/supervisord.d/auth.ini"
  notify:
    - reload supervisor

- name: deploy nginx fragment
  template:
    src: auth_params.j2
    dest: "{{ webserver_config }}/auth_params"
  notify:
    - reload nginx
