---
- name: install mariadb
  pkgng:
    name:
      - mariadb103-client
      - mariadb103-server
    cached: true

- name: copy up my.cnf
  copy:
    src: my.cnf
    dest: /var/db/mysql/
  notify:
    - restart mysql

- name: start mariadb (mysql)
  service:
    name: mysql-server
    enabled: true
    state: started
