---
# Test with:
# /usr/local/bin/tarsnap -c -f testing --dry-run -v

- name: install tarsnap
  pkgng:
    name:
      - tarsnap
      - tarsnap-periodic
    cached: true

- name: install config for tarsnap
  copy:
    src: tarsnap.conf
    dest: /usr/local/etc/

- name: copy an existing key up if it doesn't exists
  copy:
    content: "{{ vault_tarsnap_key }}"
    dest: "{{ tarsnap_key_path }}"
    owner: root
    group: wheel
    mode: 0600
    force: false
  when: vault_tarsnap_key is defined

- name: create tarsnap key if none was copied up
  shell: "tarsnap-keygen --keyfile {{ tarsnap_key_path }} --user {{ tarsnap_user }} --machine $(hostname)"
  args:
    stdin: "{{ tarsnap_password }}"
    creates: "{{ tarsnap_key_path }}"

- name: populate periodic.conf
  lineinfile:
    dest: /etc/periodic.conf
    regexp: "^#?{{ item.split('=', 1) | first }}="
    line: "{{ item }}"
  loop:
    # Daily backups are kept for only a week.
    - daily_tarsnap_backup_enable="YES"
    - daily_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - daily_tarsnap_backup_keep=7

    # Weekly backups are kept for 35 days (just over a month).
    - weekly_tarsnap_backup_enable="YES"
    - weekly_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - weekly_tarsnap_backup_keep=5

    # Keep monthly backups for six months.
    - monthly_tarsnap_backup_enable="YES"
    - monthly_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - monthly_tarsnap_backup_keep=6
