---
- name: mount all
  command: mount -a

- name: reload sshd config
  service:
    name: sshd
    state: reloaded

- name: reload syslog
  service:
    name: syslogd
    state: reloaded

- name: reload pf
  service:
    name: pf
    state: reloaded

- name: run newaliases
  command: /usr/bin/newaliases
