---
- name: install packages
  pkgng:
    name:
      - roundcube-php72
      - roundcube-sieverules-php72
      - py27-pymysql
    cached: true

- name: deploy vhost
  template:
    src: vhost.j2
    dest: "{{ webserver_config }}/vhosts/{{ webmail_site }}"
  notify:
    - reload nginx

- name: create database
  mysql_db:
    name: roundcube
    state: present
    encoding: utf8
  notify:
    - initialise roundcube database

- name: create roundcube database user
  mysql_user:
    name: roundcube
    password: "{{ webmail_db_password }}"
    priv: "roundcube.*:SELECT,INSERT,UPDATE,DELETE"

- name: deploy roundcube config
  template:
    src: roundcube.config.inc.php.j2
    dest: "/usr/local/www/roundcube/config/config.inc.php"
    owner: www
    group: www
    mode: 0700

- name: deploy managesieve config
  template:
    src: managesieve.config.inc.php.j2
    dest: "/usr/local/www/roundcube/plugins/managesieve/config.inc.php"
    owner: www
    group: www
