---
- name: install packages
  pkgng:
    name:
      - cgit
      - git-lite
    cached: true

- name: deploy configuration
  template:
    src: cgitrc.j2
    dest: /usr/local/etc/cgitrc

- name: ensure repo directory exists
  file:
    path: "{{ repos_path }}"
    state: directory
    mode: 0755

- name: deploy vhost
  template:
    src: vhost.j2
    dest: "{{ webserver_config }}/vhosts/{{ repos_site }}"
  notify:
    - reload nginx
