---
- name: install dma
  pkgng:
    name: dma
    cached: yes

- name: configure mailwrapper to use dma
  copy:
    src: mailer.conf
    dest: /etc/mail/mailer.conf

- name: periodically flush dma's queue
  cron:
    name: flush queue
    minute: '*/15'
    job: 'test -x /usr/local/libexec/dma && /usr/local/libexec/dma -q'
