---
- name: only update world and kernel
  lineinfile:
    dest: /etc/freebsd-update.conf
    regexp: "^Components "
    line: "Components world kernel"

- name: pull down updates daily
  cron:
    name: schedule freebsd-update
    special_time: daily
    job: freebsd-update cron
