---
- name: populate authorized_keys
  authorized_key:
    user: keith
    key: https://github.com/kgaughan.keys
    state: present

- name: install essential packages
  pkgng:
    name:
      - ca_root_nss
      - jq # needed by DO's bootstrap code
      - rsync
    cached: true

- name: ensure timezone is UTC
  timezone:
    name: UTC

- name: include fdesc in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^fdesc'
    line: 'fdesc /dev/fd fdescfs rw 0 0'
  notify:
    - mount all

- name: configuration directory for newsyslog
  file:
    name: /usr/local/etc/newsyslog.conf.d
    owner: root
    group: wheel
    mode: 0755
    state: directory

- import_tasks: pf.yml
- import_tasks: fbsd-update.yml
- import_tasks: ssh.yml
- import_tasks: ntimed.yml
- import_tasks: sendmail.yml
- import_tasks: recursor.yml
