---
- name: install .login_conf
  copy:
    src: login.conf
    dest: /home/keith/.login_conf
    owner: keith
    group: wheel
    mode: 0644

- name: populate authorized_keys
  authorized_key:
    user: keith
    key: https://github.com/kgaughan.keys
    state: present

- name: ensure timezone is UTC
  timezone:
    name: UTC
  when: "ansible_version.full | version_compare('2.3', '>=')"

- name: install essential packages
  pkgng:
    name: "{{ item }}"
    cached: yes
  with_items:
    - ca_root_nss
    - duff
    - lsof
    - mutt-lite
    - pkg-rmleaf
    - pwgen
    - rsync
    - tmux
    - zoneinfo

- name: include fdesc in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^fdesc'
    line: 'fdesc /dev/fd fdescfs rw 0 0'
  notify:
    - mount all

- import_tasks: pf.yml
- import_tasks: fbsd-update.yml
- import_tasks: ssh.yml
- import_tasks: ntimed.yml
- import_tasks: sendmail.yml
- import_tasks: dma.yml
  when: "'mailservers' not in group_names"
- import_tasks: tarsnap.yml
  tags:
    - tarsnap
