---
- name: install .login_conf
  copy:
    src: login.conf
    dest: /home/keith/.login_conf
    owner: keith
    group: wheel
    mode: 0644

- name: ensure timezone is UTC
  timezone:
    name: UTC
  when: "ansible_version.full | version_compare('2.3', '>=')"

- name: install essential packages
  pkgng:
    name: "{{ item }}"
    cached: yes
  with_items:
    - ca_root_nss
    - duff
    - lsof
    - mutt-lite
    - pkg-rmleaf
    - pwgen
    - rsync
    - tmux
    - zoneinfo

- name: include fdesc in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^fdesc'
    line: 'fdesc /dev/fd fdescfs rw 0 0'
  notify:
    - mount all

- include: pf.yml
- include: fbsd-update.yml
- include: ssh.yml
- include: ntimed.yml
- include: sendmail.yml
- include: dma.yml
  when: "'mailservers' not in group_names"
- include: tarsnap.yml
