---
- name: install essential packages
  pkgng:
    name: "{{ item }}"
  with_items:
    - rsync
    - tmux
    - zoneinfo

- name: include fdesc in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^fdesc'
    line: 'fdesc /dev/fd fdescfs rw 0 0'
  notify:
    - mount all

- include: pf.yml
- include: fbsd-update.yml
- include: ssh.yml
- include: ntimed.yml
- include: sendmail.yml
- include: dma.yml
  when: "'mailserver' not in group_names"
