---
- name: install ntimed
  pkgng:
    name: ntimed

- name: configure ntimed
  command: "sysrc ntimed_flags=\"{{ ntp_servers | join(' ') }}\""

- name: start ntimed
  service:
    name: ntimed
    enabled: yes
    state: started
