---
- name: install ntimed
  pkgng:
    name: ntimed
    cached: true

- name: configure ntimed
  command: "sysrc ntimed_flags=\"{{ ntp_servers | join(' ') }}\""
  changed_when: false

- name: start ntimed
  service:
    name: ntimed
    enabled: true
    state: started
