---
- name: install ntimed
  pkgng:
    name: ntimed

- name: configure ntimed
  command: sysrc ntimed_flags="0.europe.pool.ntp.org 1.europe.pool.ntp.org 2.europe.pool.ntp.org 3.europe.pool.ntp.org"

- name: start ntimed
  service:
    name: ntimed
    enabled: yes
    state: started
