---
- name: ensure legacy packages aren't present
  pkgng:
    name: sshguard-pf
    state: absent

- name: install packages
  pkgng:
    name:
      - pftop
      - sshguard
    cached: true

- name: ensure sshguard config is present
  copy:
    src: '{{ item }}'
    dest: '/usr/local/etc/'
    owner: root
    group: wheel
    mode: 0644
  loop:
    - ssh.whitelist
    - sshguard.conf
  notify:
    - reload pf
    - reload sshguard

- name: deploy pf config
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
  notify:
    - reload pf

- name: start pf
  service:
    name: pf
    enabled: true
    state: started

- name: start pflog
  service:
    name: pflog
    enabled: true
    state: started

- name: expire bruteforce blocklist entries after 2 hours of inactivity
  command: pfctl -t bruteforce -T expire 7200
  changed_when: false

- name: ensure old syslog config for sshguard is gone
  lineinfile:
    dest: /etc/syslog.conf
    regexp: sshguard
    state: absent
  notify:
    - reload syslog

- name: start sshguard
  service:
    name: sshguard
    enabled: true
    state: started
