---
- name: install sshguard
  pkgng:
    name: sshguard-pf

- name: ensure ssh whitelist is present
  file:
    path: '{{ ssh_whitelist }}'
    state: touch
    owner: root
    group: wheel
    mode: 0644

- name: deploy pf config
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf

- name: start pf
  service:
    name: pf
    enabled: yes
    state: started

- name: start pflog
  service:
    name: pflog
    enabled: yes
    state: started

- name: have sshguard listen to syslog
  lineinfile:
    dest: /etc/syslog.conf
    regexp: sshguard
    line: 'auth.info;authpriv.info |exec /usr/local/sbin/sshguard -w {{ ssh_whitelist }}'
  notify:
    - reload syslog

- name: whitelist key addresses
  lineinfile:
    dest: '{{ ssh_whitelist }}'
    line: '{{ item }}'
  with_items: '{{ ssh_whitelist_ips }}'
  notify:
    - reload pf
    - reload syslog
