---
- name: disable sendmail
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^{{ item }}'
    line: '{{ item }}="NO"'
  loop:
    - sendmail_enable
    - sendmail_submit_enable
    - sendmail_outbound_enable
    - sendmail_msp_queue_enable

- name: disable sendmail jobs
  lineinfile:
    dest: /etc/periodic.conf
    regexp: '^{{ item }}'
    line: '{{ item }}="NO"'
    create: true
  loop:
    - daily_clean_hoststat_enable
    - daily_status_mail_rejects_enable
    - daily_status_include_submit_mailq
    - daily_submit_queuerun

- name: stop sendmail
  service:
    name: sendmail
    enabled: false
    state: stopped
