---
- name: remove the ability to ssh in as root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin\\s"
    line: 'PermitRootLogin no'
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - reload sshd config

- name: disable ssh password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?\KbdInteractiveAuthentication\s"
    line: 'KbdInteractiveAuthentication no'
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - reload sshd config

- name: harden ciphers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}\\s"
    line: '{{ item.key }} {{ item["values"] | join(",") }}'
    validate: '/usr/sbin/sshd -T -f %s'
  loop:
    - key: KexAlgorithms
      values:
        - curve25519-sha256
        - curve25519-sha256@libssh.org
        - ecdh-sha2-nistp256
        - ecdh-sha2-nistp384
        - ecdh-sha2-nistp521
        - diffie-hellman-group-exchange-sha256
    - key: Ciphers
      values:
        - chacha20-poly1305@openssh.com
        - aes128-gcm@openssh.com
        - aes256-gcm@openssh.com
    - key: MACs
      values:
        - umac-128-etm@openssh.com
        - hmac-sha2-256-etm@openssh.com
        - hmac-sha2-512-etm@openssh.com
        - hmac-sha1-etm@openssh.com
        - umac-128@openssh.com
        - hmac-sha2-256
        - hmac-sha2-512
  notify:
    - reload sshd config
