---
- name: remove the ability to ssh in as root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin\\s"
    line: 'PermitRootLogin no'
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - reload sshd config

- name: disable ssh password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication\\s"
    line: 'ChallengeResponseAuthentication no'
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - reload sshd config

- name: harden ciphers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}\\s"
    line: '{{ item.key }} {{ item["values"] | join(",") }}'
    validate: '/usr/sbin/sshd -T -f %s'
  loop:
    - key: KexAlgorithms
      values:
        - curve25519-sha256@libssh.org
        - diffie-hellman-group-exchange-sha256
    - key: Ciphers
      values:
        - chacha20-poly1305@openssh.com
        - aes256-gcm@openssh.com
        - aes128-gcm@openssh.com
        - aes256-ctr
        - aes192-ctr
        - aes128-ctr
    - key: MACs
      values:
        - hmac-sha2-512-etm@openssh.com
        - hmac-sha2-256-etm@openssh.com
        - umac-128-etm@openssh.com
        - hmac-sha2-512
        - hmac-sha2-256
  notify:
    - reload sshd config
