---
- name: install tarsnap
  pkgng:
    name: "{{ item }}"
    cached: yes
  with_items:
    - tarsnap
    - tarsnap-periodic

- name: install config for tarsnap
  copy:
    src: tarsnap.conf
    dest: /usr/local/etc/

- name: populate periodic.conf
  lineinfile:
    dest: /etc/periodic.conf
    regexp: "^#?{{ item.split('=', 1) | first }}="
    line: "{{ item }}"
  with_items:
    - daily_tarsnap_backup_enable="NO"
    - daily_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - daily_tarsnap_backup_keep=7
    - weekly_tarsnap_backup_enable="NO"
    - weekly_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - weekly_tarsnap_backup_keep=5
    - monthly_tarsnap_backup_enable="NO"
    - monthly_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - monthly_tarsnap_backup_keep=6
