---
# Test with:
# /usr/local/bin/tarsnap -c -f testing --dry-run -v

- name: install tarsnap
  pkgng:
    name:
      - tarsnap
      - tarsnap-periodic
    cached: true

- name: install config for tarsnap
  copy:
    src: tarsnap.conf
    dest: /usr/local/etc/

- name: check if the tarsnap key file exists
  stat:
    path: "{{ tarsnap_key_path }}"
    get_attributes: false
    get_checksum: false
    get_md5: false
    get_mime: false
  register: key_stat

- block:
    - name: copy existing key up if it doesn't exists
      copy:
        content: "{{ vault_tarsnap_key }}"
        dest: "{{ tarsnap_key_path }}"
        owner: root
        group: wheel
        mode: 0600
        backup: true
      when: vault_tarsnap_key is defined

    - debug:
        msg: "Please run: sudo tarsnap-keygen --keyfile {{ tarsnap_key_path }} --user {{ tarsnap_user }} --machine $(hostname)"
      when: vault_tarsnap_key is not defined
  when: not key_stat.stat.exists

- name: populate periodic.conf
  lineinfile:
    dest: /etc/periodic.conf
    regexp: "^#?{{ item.split('=', 1) | first }}="
    line: "{{ item }}"
  loop:
    # Daily backups are kept for only a week.
    - daily_tarsnap_backup_enable={{ "YES" if backup_enabled else "NO" }}
    - daily_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - daily_tarsnap_backup_keep=7

    # Weekly backups are kept for 35 days (just over a month).
    - weekly_tarsnap_backup_enable={{ "YES" if backup_enabled else "NO" }}
    - weekly_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - weekly_tarsnap_backup_keep=5

    # Keep monthly backups for six months.
    - monthly_tarsnap_backup_enable={{ "YES" if backup_enabled else "NO" }}
    - monthly_tarsnap_backup_paths="{{ backup_locations | join(' ') }}"
    - monthly_tarsnap_backup_keep=6
