---
- name: restart postfix
  service:
    name: postfix
    state: reloaded

- name: restart dovecot
  service:
    name: dovecot
    state: reloaded

- name: restart rspamd
  service:
    name: rspamd
    enabled: yes
    state: reloaded
