---
- name: install packages
  pkgng:
    name:
      - php83
      - php83-opcache  # recommended
    cached: true
  notify:
    - reload php_fpm

- name: copy up upstream php_fpm socket config
  copy:
    src: php_socket
    dest: "{{ webserver_config }}/extra/"
  notify:
    - reload nginx

- name: copy up vhost config fragment
  copy:
    src: php_params
    dest: "{{ webserver_config }}/"
  notify:
    - reload nginx

- name: copy up php-fpm.conf
  copy:
    src: php-fpm.conf
    dest: "/usr/local/etc/"
  notify:
    - reload php_fpm

- name: start php_fpm
  service:
    name: php_fpm
    enabled: true
    state: started
