---
- name: copy up periodic task
  template:
    src: weekly.j2
    dest: "/usr/local/etc/periodic/weekly/000.acme-tiny.sh"
    mode: 0755

- name: copy up renewal script
  copy:
    src: acme-domain-renew
    dest: "{{ acme_client_root }}"
    mode: 0555

- name: generate the deploy script
  lineinfile:
    path: "{{ acme_client_root }}/deploy.sh"
    mode: 0555
    create: true
    state: present
    insertbefore: BOF
    line: "#!/bin/sh"

- name: restart webserver on cert deployment
  lineinfile:
    path: "{{ acme_client_root }}/deploy.sh"
    state: present
    insertafter: EOF
    line: "service nginx reload"

- name: populate domains.txt
  lineinfile:
    dest: "{{ acme_client_root }}/domains.txt"
    create: true
    regexp: "^{{ item }} ?"
    line: "{{ item | acme_list(acme_domains[item]) | join(' ') }}"
  loop: "{{ acme_domains.keys() | list }}"
  notify:
    - generate missing certificates

- name: populate periodic.conf
  lineinfile:
    dest: /etc/periodic.conf
    regexp: "^#?{{ item.split('=', 1) | first }}="
    line: "{{ item }}"
  loop:
    - weekly_acme_tiny_enable="YES"
