---
- name: install package
  pkgng:
    name:
      - fcgiwrap
    cached: true

- name: push up fcgiwrap config
  command: "sysrc {{ item }}"
  loop:
    - fcgiwrap_user="www"
    - fcgiwrap_socket_owner="www"
  changed_when: false

- name: start the service
  service:
    name: fcgiwrap
    enabled: true
    state: started
