---
- name: common
  hosts: all
  remote_user: keith
  become: false

  vars:
    ansible_python_interpreter: /usr/local/bin/python3

  tasks:
    - name: install packages
      pkgng:
        name:
          - pkg-rmleaf
          - tmux
        cached: true
      become: true

    - name: install user configuration files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        mode: "0640"
      loop:
        - login_conf
        - nexrc
        - tmux.conf
        - cshrc
        - login
      loop_control:
        label: ".{{ item }}"

    - name: directory for scripts
      file:
        path: "{{ ansible_env.HOME }}/bin"
        state: directory

    - name: install scripts
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/bin/{{ item }}"
        mode: "0750"
      loop:
        - pkgupdate
        - flush-table
      loop_control:
        label: "{{ item }}"

- name: irssi
  hosts:
    - lir.talideon.com
  remote_user: keith
  become: false

  vars:
    ansible_python_interpreter: /usr/local/bin/python3

  tasks:
    - name: install packages
      pkgng:
        name:
          - irssi
        cached: true
      become: true

    - name: config directory
      file:
        path: "{{ ansible_env.HOME }}/.irssi/scripts"
        state: directory

    - name: deploy theme
      copy:
        src: "irssi/solarized-universal.theme"
        dest: "{{ ansible_env.HOME }}/.irssi/solarized-universal.theme"
        mode: "0640"

    - name: deploy configuration
      template:
        src: "irssi/config.j2"
        dest: "{{ ansible_env.HOME }}/.irssi/config"
        mode: "0600"

- name: fdm
  hosts:
    - manann.talideon.com
  remote_user: keith
  become: false

  vars:
    ansible_python_interpreter: /usr/local/bin/python3

  tasks:
    - name: install packages
      pkgng:
        name:
          - fdm
        cached: true
      become: true

    - name: install configuration
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        mode: "0640"
      loop:
        - fdm.conf
      loop_control:
        label: ".{{ item }}"

    - name: add credentials
      lineinfile:
        path: "{{ ansible_env.HOME }}/.netrc"
        create: true
        mode: "0600"
        regexp: "^machine webmail.eir.ie "
        line: "machine webmail.eir.ie login {{ fdm.username }} password {{ fdm.password }}"

    - name: periodically run
      cron:
        name: run fdm
        minute: "0"
        hour: "*/3"
        job: "/usr/bin/nice -n 19 /usr/local/bin/fdm -l fetch"
