---
- name: common
  hosts: all
  remote_user: keith
  become: false

  tasks:
    - name: populate authorized_keys
      authorized_key:
        key: https://github.com/kgaughan.keys
        user: "{{ ansible_user }}"
        state: present

    - name: ensure SSH key exists
      openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
        type: ed25519

    - name: install user configuration files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        mode: "0640"
      loop:
        - login_conf
        - nexrc
        - tmux.conf
        - cshrc
        - login
        - ssh/config
      loop_control:
        label: ".{{ item }}"

- name: managed
  hosts:
    - freebsd
  remote_user: keith
  become: false

  tasks:
    - name: install packages
      pkgng:
        name:
          - pkg-rmleaf
          - tmux
        cached: true
      become: true

    - name: directory for scripts
      file:
        path: "{{ ansible_env.HOME }}/bin"
        state: directory

    - name: install scripts
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/bin/{{ item }}"
        mode: "0750"
      loop:
        - pkg-update
        - flush-table
      loop_control:
        label: "{{ item }}"

- name: irssi
  hosts:
    - lir.talideon.com
  remote_user: keith
  become: false

  tasks:
    - name: install packages
      pkgng:
        name:
          - irssi
        cached: true
      become: true

    - name: config directory
      file:
        path: "{{ ansible_env.HOME }}/.irssi/scripts"
        state: directory

    - name: deploy theme
      copy:
        src: "irssi/solarized-universal.theme"
        dest: "{{ ansible_env.HOME }}/.irssi/solarized-universal.theme"
        mode: "0640"

    - name: deploy configuration
      template:
        src: "irssi/config.j2"
        dest: "{{ ansible_env.HOME }}/.irssi/config"
        mode: "0600"

- name: vbox management
  hosts:
    - mailservers
  remote_user: keith
  become: false

  tasks:
    - name: directory for scripts
      file:
        path: "{{ ansible_env.HOME }}/bin"
        state: directory

    - name: install scripts
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/bin/{{ item }}"
        mode: "0750"
      loop:
        - manage-vbox
      loop_control:
        label: "{{ item }}"
